/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.border.LineBorder;
import model.Disciplina;

/**
 *
 * @author lasagnil
 */
public class InserisciAppello extends javax.swing.JDialog {
    
    Home H = new Home();

    /**
     * Creates new form InserisciCorso
     */
    public InserisciAppello(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        H = (Home)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitoloMain = new javax.swing.JLabel();
        InputAppelloId = new javax.swing.JTextField();
        InputAppelloData = new javax.swing.JTextField();
        InputAppelloDisciplina = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Carica = new javax.swing.JButton();
        ErrorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("InserisciAppello");

        TitoloMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloMain.setText("Inserisci nuovo appello");

        InputAppelloId.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        InputAppelloData.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        InputAppelloDisciplina.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        InputAppelloDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAppelloDisciplinaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Identificatore");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Codice Disciplina");

        Carica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Carica.setText("Carica");
        Carica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaricaActionPerformed(evt);
            }
        });

        ErrorText.setForeground(new java.awt.Color(204, 0, 0));
        ErrorText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InputAppelloData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(InputAppelloId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputAppelloDisciplina)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(TitoloMain)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carica, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputAppelloId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputAppelloData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputAppelloDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addComponent(Carica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaricaActionPerformed
        String id = InputAppelloId.getText();
        String data = InputAppelloData.getText();
        String disciplina = InputAppelloDisciplina.getText();
        
        boolean b_id = false, b_data=false, b_disciplina=false;
        
        Disciplina d = H.getGestore().controlloDisciplina(disciplina);
        
        if (id.equals("")) {
            InputAppelloId.setBorder(new LineBorder(Color.red, 3));
            b_id=false;
            ErrorText.setText("Parametro/i mancante/i");
        }
        else {
            InputAppelloId.setBorder(new LineBorder(Color.black, 1));
            b_id=true;
        }
        
        if (data.equals("")) {
            InputAppelloData.setBorder(new LineBorder(Color.red, 3));
            b_data=false;
            ErrorText.setText("Parametro/i mancante/i");
        }
        else {
            InputAppelloData.setBorder(new LineBorder(Color.black, 1));
            b_data=true;
        }
        
        if (disciplina.equals("") || d==null) {
            InputAppelloDisciplina.setBorder(new LineBorder(Color.red, 3));
            b_disciplina=false;
            ErrorText.setText("Parametro/i mancante/i");
            if (d==null && !data.equals("") && !id.equals("") && !disciplina.equals("")) ErrorText.setText("Codice disciplina errato");
        }
        else {
            InputAppelloDisciplina.setBorder(new LineBorder(Color.black, 1));
            b_disciplina=true;
        }
        
        if (b_id && b_data && b_disciplina) {
            H.getGestore().aggiungiAppello(id, data, d);
            H.getText().setText(H.getGestore().stampaAppelli());
            this.setVisible(false);
        }
    
    }//GEN-LAST:event_CaricaActionPerformed

    private void InputAppelloDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAppelloDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAppelloDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserisciAppello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserisciAppello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserisciAppello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserisciAppello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserisciAppello dialog = new InserisciAppello(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carica;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JTextField InputAppelloData;
    private javax.swing.JTextField InputAppelloDisciplina;
    private javax.swing.JTextField InputAppelloId;
    private javax.swing.JLabel TitoloMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
