/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Gestore; // importa la classe Gestore da un altro package
import java.awt.Color;
import javax.swing.border.LineBorder; // usati per personalizzare i bordi e i colori dei componenti 

/**
 *
 * @author lasagnil
 */
public class ModificaCorso extends javax.swing.JDialog {

    Home H = new Home();

    /**
     * Creates new form InserisciCorso
     */
    public ModificaCorso(java.awt.Frame parent, boolean modal) {
        super(parent, modal); // chiama il costruttore del padre
        H = (Home) parent; // assegna l'oggetto Home passato come parent
        initComponents(); // inizializza i componenti grafici

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitoloMain = new javax.swing.JLabel();
        InputCorsoCodice = new javax.swing.JTextField();
        InputCorsoNome = new javax.swing.JTextField();
        InputCorsoDurata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Modifica = new javax.swing.JButton();
        ErrorText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ModificaCorso");

        TitoloMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloMain.setText("Modifica corso");

        InputCorsoCodice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InputCorsoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InputCorsoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCorsoNomeActionPerformed(evt);
            }
        });

        InputCorsoDurata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InputCorsoDurata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCorsoDurataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Codice");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Durata");

        Modifica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Modifica.setText("Modifica");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        ErrorText.setForeground(new java.awt.Color(204, 0, 0));
        ErrorText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("(base di modifica)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputCorsoDurata, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(InputCorsoNome)
                    .addComponent(InputCorsoCodice))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TitoloMain)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Modifica)
                            .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCorsoCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCorsoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputCorsoDurata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addComponent(Modifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // eseguito quando si clicca il bottone "Carica" e recupera i dati inseriti:
    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CaricaActionPerformed

        // Controlla se i campi sono vuoti o non validi, colora il bordo in rosso se mancano dati, mostra messaggi d’errore e verifica che la durata sia numerica (Integer.parseInt con try-catch)

        String codice = InputCorsoCodice.getText();
        String nome = InputCorsoNome.getText();
        String durata = InputCorsoDurata.getText();

        Integer durata_int;

        boolean b_codice = false, b_nome = false, b_durata = false;

        if (codice.equals("")) {
            InputCorsoCodice.setBorder(new LineBorder(Color.red, 3));
            b_codice = false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            InputCorsoCodice.setBorder(new LineBorder(Color.black, 1));
            b_codice = true;
        }

        if (nome.equals("")) {
            InputCorsoNome.setBorder(new LineBorder(Color.red, 3));
            b_nome = false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            InputCorsoNome.setBorder(new LineBorder(Color.black, 1));
            b_nome = true;
        }

        if (durata.equals("")) {
            InputCorsoDurata.setBorder(new LineBorder(Color.red, 3));
            b_durata = false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            boolean d_i = true;

            try {
                durata_int = Integer.parseInt(durata);
            } catch (NumberFormatException e) {
                d_i = false;
            }

            if (d_i) {
                b_durata = true;
                InputCorsoDurata.setBorder(new LineBorder(Color.black, 1));
            } else {
                if (!codice.equals("") && !nome.equals(""))
                    ErrorText.setText("E' richiesto un valore numerico");
                InputCorsoDurata.setBorder(new LineBorder(Color.red, 3));
            }
        }

        if (b_codice && b_nome && b_durata) {
            //chiama il metodo aggiungiCorso del Gestore e chiude la finestra.
            H.getGestore().modificaCorso(codice, nome, Integer.parseInt(durata));
            H.getText().setText(H.getGestore().stampaCorsi());
            this.setVisible(false);
        }
    }// GEN-LAST:event_CaricaActionPerformed

    private void InputCorsoNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InputCorsoNomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_InputCorsoNomeActionPerformed

    private void InputCorsoDurataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InputCorsoDurataActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_InputCorsoDurataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaCorso.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaCorso.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaCorso.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaCorso.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificaCorso dialog = new ModificaCorso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                //crea e mostra la finestra InserisciCorso
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorText;
    private javax.swing.JTextField InputCorsoCodice;
    private javax.swing.JTextField InputCorsoDurata;
    private javax.swing.JTextField InputCorsoNome;
    private javax.swing.JButton Modifica;
    private javax.swing.JLabel TitoloMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
