/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import model.*;

/**
 *
 * @author lasagnil
 */
public class Home extends javax.swing.JFrame {

    Gestore g = new Gestore();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        g.caricaCorsi();
        g.caricaDiscipline();
        g.caricaStudenti();
        g.caricaDocenti();
        g.caricaAppelli();
        g.caricaIscrizioni();

    }

    public Gestore getGestore() {
        return g;
    }
    
    public javax.swing.JTextPane getText() {
        return this.TextView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitoloMain = new javax.swing.JLabel();
        SubCorsi = new javax.swing.JLabel();
        SubDocenti = new javax.swing.JLabel();
        SubDiscipline = new javax.swing.JLabel();
        SubStudenti = new javax.swing.JLabel();
        SubAppelli = new javax.swing.JLabel();
        CorsiView = new javax.swing.JButton();
        CorsiAggiungi = new javax.swing.JButton();
        DisciplineView = new javax.swing.JButton();
        DisciplineAggiungi = new javax.swing.JButton();
        DocentiView = new javax.swing.JButton();
        DocentiAggiungi = new javax.swing.JButton();
        StudentiView = new javax.swing.JButton();
        StudentiAggiungi = new javax.swing.JButton();
        AppelliView = new javax.swing.JButton();
        AppelliAggiungi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextView = new javax.swing.JTextPane();
        AppelliModifica = new javax.swing.JButton();
        StudentiModifica = new javax.swing.JButton();
        DocentiModifica = new javax.swing.JButton();
        DisciplineModifica = new javax.swing.JButton();
        CorsiModifica = new javax.swing.JButton();
        Svuota = new javax.swing.JButton();
        SubAppelli1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        setResizable(false);

        TitoloMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitoloMain.setText("Pagina Principale");

        SubCorsi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubCorsi.setText("Corsi");

        SubDocenti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubDocenti.setText("Docenti");

        SubDiscipline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubDiscipline.setText("Discipline");

        SubStudenti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubStudenti.setText("Studenti");

        SubAppelli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubAppelli.setText("Appelli");

        CorsiView.setText("Visualizza");
        CorsiView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorsiViewActionPerformed(evt);
            }
        });

        CorsiAggiungi.setText("Aggiungi");
        CorsiAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorsiAggiungiActionPerformed(evt);
            }
        });

        DisciplineView.setText("Visualizza");
        DisciplineView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciplineViewActionPerformed(evt);
            }
        });

        DisciplineAggiungi.setText("Aggiungi");
        DisciplineAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciplineAggiungiActionPerformed(evt);
            }
        });

        DocentiView.setText("Visualizza");
        DocentiView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentiViewActionPerformed(evt);
            }
        });

        DocentiAggiungi.setText("Aggiungi");
        DocentiAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentiAggiungiActionPerformed(evt);
            }
        });

        StudentiView.setText("Visualizza");
        StudentiView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentiViewActionPerformed(evt);
            }
        });

        StudentiAggiungi.setText("Aggiungi");
        StudentiAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentiAggiungiActionPerformed(evt);
            }
        });

        AppelliView.setText("Visualizza");
        AppelliView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppelliViewActionPerformed(evt);
            }
        });

        AppelliAggiungi.setText("Aggiungi");
        AppelliAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppelliAggiungiActionPerformed(evt);
            }
        });

        TextView.setEditable(false);
        TextView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(TextView);

        AppelliModifica.setText("Modifica");
        AppelliModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppelliModificaActionPerformed(evt);
            }
        });

        StudentiModifica.setText("Modifica");
        StudentiModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentiModificaActionPerformed(evt);
            }
        });

        DocentiModifica.setText("Modifica");
        DocentiModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentiModificaActionPerformed(evt);
            }
        });

        DisciplineModifica.setText("Modifica");
        DisciplineModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciplineModificaActionPerformed(evt);
            }
        });

        CorsiModifica.setText("Modifica");
        CorsiModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorsiModificaActionPerformed(evt);
            }
        });

        Svuota.setText("Svuota");
        Svuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SvuotaActionPerformed(evt);
            }
        });

        SubAppelli1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SubAppelli1.setText("Svuota visualizzazione");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubCorsi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubStudenti)
                            .addComponent(SubAppelli))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubDocenti)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(AppelliView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(StudentiView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DocentiView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SubDiscipline, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CorsiView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DisciplineView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CorsiAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DisciplineAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DocentiAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(StudentiAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AppelliAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(SubAppelli1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Svuota)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(AppelliModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DisciplineModifica)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(StudentiModifica, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DocentiModifica, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(CorsiModifica))))))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(TitoloMain)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubCorsi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorsiView)
                            .addComponent(CorsiAggiungi)
                            .addComponent(CorsiModifica))
                        .addGap(24, 24, 24)
                        .addComponent(SubDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DisciplineView)
                            .addComponent(DisciplineAggiungi)
                            .addComponent(DisciplineModifica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(SubDocenti, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DocentiView)
                            .addComponent(DocentiAggiungi)
                            .addComponent(DocentiModifica))
                        .addGap(24, 24, 24)
                        .addComponent(SubStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentiView)
                            .addComponent(StudentiAggiungi)
                            .addComponent(StudentiModifica))
                        .addGap(24, 24, 24)
                        .addComponent(SubAppelli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AppelliView)
                            .addComponent(AppelliAggiungi)
                            .addComponent(AppelliModifica))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Svuota)
                            .addComponent(SubAppelli1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorsiViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorsiViewActionPerformed
        this.TextView.setText(g.stampaCorsi());
    }//GEN-LAST:event_CorsiViewActionPerformed

    private void DisciplineAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciplineAggiungiActionPerformed
        InserisciDisciplina id = new InserisciDisciplina(this, true);
        id.setVisible(true);
    }//GEN-LAST:event_DisciplineAggiungiActionPerformed

    private void CorsiAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorsiAggiungiActionPerformed
        InserisciCorso ic = new InserisciCorso(this, true);
        ic.setVisible(true);
    }//GEN-LAST:event_CorsiAggiungiActionPerformed

    private void DisciplineViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciplineViewActionPerformed
        this.TextView.setText(g.stampaDiscipline());
    }//GEN-LAST:event_DisciplineViewActionPerformed

    private void DocentiViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentiViewActionPerformed
        this.TextView.setText(g.stampaDocenti());
    }//GEN-LAST:event_DocentiViewActionPerformed

    private void DocentiAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentiAggiungiActionPerformed
        InserisciDocente idoc = new InserisciDocente(this, true);
        idoc.setVisible(true);
    }//GEN-LAST:event_DocentiAggiungiActionPerformed

    private void StudentiViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentiViewActionPerformed
        this.TextView.setText(g.stampaStudenti());
    }//GEN-LAST:event_StudentiViewActionPerformed

    private void StudentiAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentiAggiungiActionPerformed
        InserisciStudente is = new InserisciStudente(this, true);
        is.setVisible(true);
    }//GEN-LAST:event_StudentiAggiungiActionPerformed

    private void AppelliViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppelliViewActionPerformed
        this.TextView.setText(g.stampaAppelli());
    }//GEN-LAST:event_AppelliViewActionPerformed

    private void AppelliAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppelliAggiungiActionPerformed
        InserisciAppello ia = new InserisciAppello(this, true);
        ia.setVisible(true);
    }//GEN-LAST:event_AppelliAggiungiActionPerformed

    private void AppelliModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppelliModificaActionPerformed
        ModificaAppello ma = new ModificaAppello(this, true);
        ma.setVisible(true);
    }//GEN-LAST:event_AppelliModificaActionPerformed

    private void StudentiModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentiModificaActionPerformed
        ModificaStudente ms = new ModificaStudente(this, true);
        ms.setVisible(true);
    }//GEN-LAST:event_StudentiModificaActionPerformed

    private void DocentiModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentiModificaActionPerformed
        ModificaDocente md = new ModificaDocente(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_DocentiModificaActionPerformed

    private void DisciplineModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciplineModificaActionPerformed
        ModificaDisciplina md2 = new ModificaDisciplina(this, true);
        md2.setVisible(true);
    }//GEN-LAST:event_DisciplineModificaActionPerformed

    private void CorsiModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorsiModificaActionPerformed
        ModificaCorso mc = new ModificaCorso(this, true);
        mc.setVisible(true);
    }//GEN-LAST:event_CorsiModificaActionPerformed

    private void SvuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SvuotaActionPerformed
        TextView.setText("");
    }//GEN-LAST:event_SvuotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppelliAggiungi;
    private javax.swing.JButton AppelliModifica;
    private javax.swing.JButton AppelliView;
    private javax.swing.JButton CorsiAggiungi;
    private javax.swing.JButton CorsiModifica;
    private javax.swing.JButton CorsiView;
    private javax.swing.JButton DisciplineAggiungi;
    private javax.swing.JButton DisciplineModifica;
    private javax.swing.JButton DisciplineView;
    private javax.swing.JButton DocentiAggiungi;
    private javax.swing.JButton DocentiModifica;
    private javax.swing.JButton DocentiView;
    private javax.swing.JButton StudentiAggiungi;
    private javax.swing.JButton StudentiModifica;
    private javax.swing.JButton StudentiView;
    private javax.swing.JLabel SubAppelli;
    private javax.swing.JLabel SubAppelli1;
    private javax.swing.JLabel SubCorsi;
    private javax.swing.JLabel SubDiscipline;
    private javax.swing.JLabel SubDocenti;
    private javax.swing.JLabel SubStudenti;
    private javax.swing.JButton Svuota;
    private javax.swing.JTextPane TextView;
    private javax.swing.JLabel TitoloMain;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
