/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.border.LineBorder;
import model.Corso;

/**
 *
 * @author lasagnil
 */
public class InserisciDisciplina extends javax.swing.JDialog {
    
    Home H = new Home();

    /**
     * Creates new form InserisciCorso
     */
    public InserisciDisciplina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        H = (Home)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Carica = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InputDisciplinaCfu = new javax.swing.JTextField();
        ErrorText = new javax.swing.JLabel();
        TitoloMain = new javax.swing.JLabel();
        InputDisciplinaCodice = new javax.swing.JTextField();
        InputDisciplinaNome = new javax.swing.JTextField();
        InputDisciplinaCorso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("InserisciDiscipline");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CFU");

        Carica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Carica.setText("Carica");
        Carica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaricaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Codice corso");

        InputDisciplinaCfu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ErrorText.setForeground(new java.awt.Color(204, 0, 0));
        ErrorText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TitoloMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloMain.setText("Inserisci nuova disciplina");

        InputDisciplinaCodice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InputDisciplinaNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InputDisciplinaCorso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InputDisciplinaCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDisciplinaCorsoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Codice");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputDisciplinaCfu, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(InputDisciplinaCorso))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(InputDisciplinaNome)
                    .addComponent(InputDisciplinaCodice))
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(TitoloMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carica, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputDisciplinaCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputDisciplinaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputDisciplinaCfu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputDisciplinaCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(Carica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaricaActionPerformed
        String codice = InputDisciplinaCodice.getText();
        String nome = InputDisciplinaNome.getText();
        String cfu = InputDisciplinaCfu.getText();
        String corso = InputDisciplinaCorso.getText();

        Integer cfu_int; // CFU convertito in intero

        // Flag per i controlli
        boolean b_codice = false, b_nome=false, b_cfu=false, b_corso=false;

        // Controlla se il codice del corso esiste
        Corso c = H.getGestore().controlloCorso(corso);

        // Validazione campo codice
        if (codice.equals("")) {
            InputDisciplinaCodice.setBorder(new LineBorder(Color.red, 3));
            b_codice=false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            InputDisciplinaCodice.setBorder(new LineBorder(Color.black, 1));
            b_codice=true;
        }

        // Validazione campo nome
        if (nome.equals("")) {
            InputDisciplinaNome.setBorder(new LineBorder(Color.red, 3));
            b_nome=false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            InputDisciplinaNome.setBorder(new LineBorder(Color.black, 1));
            b_nome=true;
        }

        // Validazione campo CFU
        if (cfu.equals("")) {
            InputDisciplinaCfu.setBorder(new LineBorder(Color.red, 3));
            b_cfu=false;
            ErrorText.setText("Parametro/i mancante/i");
        } else {
            boolean c_i = true;
            try {
                cfu_int = Integer.parseInt(cfu); // tenta conversione in intero
            } catch (NumberFormatException e) {
                c_i=false;
            }

            if (c_i) {
                b_cfu=true;
                InputDisciplinaCfu.setBorder(new LineBorder(Color.black, 1));
            } else {
                // Se CFU non è numerico
                if (!codice.equals("") && !nome.equals("") && !corso.equals("")) 
                    ErrorText.setText("E' richiesto un valore numerico");
                InputDisciplinaCfu.setBorder(new LineBorder(Color.red, 3));
            }
        }

        // Validazione campo codice corso
        if (corso.equals("") || c==null) {
            InputDisciplinaCorso.setBorder(new LineBorder(Color.red, 3));
            b_corso=false;
            ErrorText.setText("Parametro/i mancante/i");
            if (c==null && !codice.equals("") && !nome.equals("") && !cfu.equals("") && !corso.equals("")) 
                ErrorText.setText("Codice corso errato");
        } else {
            InputDisciplinaCorso.setBorder(new LineBorder(Color.black, 1));
            b_corso=true;
        }

        // Se tutti i controlli sono validi, aggiunge la disciplina
        if (b_codice && b_nome && b_cfu && b_corso) {
            H.getGestore().aggiungiDisciplina(codice, nome, Integer.parseInt(cfu), c);
            H.getText().setText(H.getGestore().stampaDiscipline());
            this.setVisible(false); // chiude la finestra
        }
    }//GEN-LAST:event_CaricaActionPerformed

    private void InputDisciplinaCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDisciplinaCorsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDisciplinaCorsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserisciDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserisciDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserisciDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserisciDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserisciDisciplina dialog = new InserisciDisciplina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carica;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JTextField InputDisciplinaCfu;
    private javax.swing.JTextField InputDisciplinaCodice;
    private javax.swing.JTextField InputDisciplinaCorso;
    private javax.swing.JTextField InputDisciplinaNome;
    private javax.swing.JLabel TitoloMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
