/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.border.LineBorder;
import model.Corso;

/**
 *
 * @author lasagnil
 */
public class InserisciStudente extends javax.swing.JDialog {
    
    Home H = new Home();

    /**
     * Creates new form InserisciCorso
     */
    public InserisciStudente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        H = (Home)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitoloMain = new javax.swing.JLabel();
        InputStudenteMatricola = new javax.swing.JTextField();
        InputStudenteNome = new javax.swing.JTextField();
        InputStudenteCorso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Carica = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InputStudenteCognome = new javax.swing.JTextField();
        ErrorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("InserisciStudente");

        TitoloMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloMain.setText("Inserisci nuovo studente");

        InputStudenteMatricola.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        InputStudenteMatricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStudenteMatricolaActionPerformed(evt);
            }
        });

        InputStudenteNome.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        InputStudenteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStudenteNomeActionPerformed(evt);
            }
        });

        InputStudenteCorso.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        InputStudenteCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStudenteCorsoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Matricola");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cognome");

        Carica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Carica.setText("Carica");
        Carica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaricaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Codice corso");

        InputStudenteCognome.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        ErrorText.setForeground(new java.awt.Color(204, 0, 0));
        ErrorText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ErrorText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputStudenteCognome, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(InputStudenteCorso))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(InputStudenteNome)
                    .addComponent(InputStudenteMatricola))
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(TitoloMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carica))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStudenteMatricola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputStudenteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputStudenteCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputStudenteCorso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(Carica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaricaActionPerformed
        String matricola = InputStudenteMatricola.getText();
        String nome = InputStudenteNome.getText();
        String cognome = InputStudenteCognome.getText();
        String corso = InputStudenteCorso.getText();

        boolean b_matricola = false, b_nome=false, b_cognome=false, b_corso=false;
        
        Corso c = H.getGestore().controlloCorso(corso);
        
        if (matricola.equals("")) {
            InputStudenteMatricola.setBorder(new LineBorder(Color.red, 3));
            b_matricola=false;
            ErrorText.setText("Parametro/i mancante/i");
        }
        else {
            InputStudenteMatricola.setBorder(new LineBorder(Color.black, 1));
            b_matricola=true;
        }
        
        if (nome.equals("")) {
            InputStudenteNome.setBorder(new LineBorder(Color.red, 3));
            b_nome=false;
            ErrorText.setText("Parametro/i mancante/i");
        }
        else {
            InputStudenteNome.setBorder(new LineBorder(Color.black, 1));
            b_nome=true;
        }
        
        if (cognome.equals("")) {
            InputStudenteCognome.setBorder(new LineBorder(Color.red, 3));
            b_cognome=false;
            ErrorText.setText("Parametro/i mancante/i");
        }
        else {
            InputStudenteCognome.setBorder(new LineBorder(Color.black, 1));
            b_cognome=true;
        }
        
        if (corso.equals("") || c==null) {
            InputStudenteCorso.setBorder(new LineBorder(Color.red, 3));
            b_corso=false;
            ErrorText.setText("Parametro/i mancante/i");
            if (c==null && !matricola.equals("") && !nome.equals("") && !cognome.equals("") && !corso.equals("")) ErrorText.setText("Codice corso errato");
        }
        else {
            InputStudenteCorso.setBorder(new LineBorder(Color.black, 1));
            b_corso=true;
        }
        
        if (b_matricola && b_nome && b_cognome && b_corso) {
            H.getGestore().aggiungiStudente(matricola, nome, cognome, c);
            H.getText().setText(H.getGestore().stampaStudenti());
            this.setVisible(false);
        }
    }//GEN-LAST:event_CaricaActionPerformed

    private void InputStudenteCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStudenteCorsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStudenteCorsoActionPerformed

    private void InputStudenteMatricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStudenteMatricolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStudenteMatricolaActionPerformed

    private void InputStudenteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStudenteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStudenteNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserisciStudente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserisciStudente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserisciStudente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserisciStudente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserisciStudente dialog = new InserisciStudente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carica;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JTextField InputStudenteCognome;
    private javax.swing.JTextField InputStudenteCorso;
    private javax.swing.JTextField InputStudenteMatricola;
    private javax.swing.JTextField InputStudenteNome;
    private javax.swing.JLabel TitoloMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
